### ISSUE TITLE
We need to pick a license

### ISSUE THREAD

**Issue by benthillerkus** [benthillerkus/SpaceLovers#41]
Since we are using the Processing Sound library (and shipping it), just picking a GPL-compatible license for the code should be the easiest.
Both the art assets and the music could be licensed under different licenses such as some Creative Commons license.
>> https://creativecommons.org/choose/?lang=de

The fonts I picked are all under the OFL, and we are shipping their respective licenses with the project, so this is fine.

**Comment by benthillerkus** [comment]
Ok anscheinend sind Minim und Processing-Sound nur LGPL, dh wir hätten freie Wahl gehabt, was den Code betrifft, aber die GPL ist imo gut

**Comment by Natapata** [comment]
SpaceLovers © 2021 by Bent HIllerkus, Joshua Lasse Einhoff, Natalie Turek and Kevin Kader Josh  is licensed under CC BY-NC-SA 4.0 ? reicht das?
